project_id = "mtmrsmbjllrfmduztofj"

[functions.interior-ai]
verify_jwt = false

[functions.exterior-ai]
verify_jwt = false

[functions.sketch-to-img]
verify_jwt = false

[functions.inpainting-ai]
verify_jwt = false

[functions.imagine-ai]
verify_jwt = false

[functions.style-transfer]
verify_jwt = false

[functions.render-enhancer]
verify_jwt = false

[functions.virtual-staging]
verify_jwt = false

[functions.ai-eraser]
verify_jwt = false

[functions.four-k-upscaler]
verify_jwt = false

[functions.check-status]
verify_jwt = false

[functions.prompt-generator]
verify_jwt = false

[functions.video-ai]
verify_jwt = false
